# Generated by Django 4.2.20 on 2025-04-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='Subscribe',
        ),
    ]
